spring:
  application:
    name: web-application-chat
  mvc:
    async:
      request-timeout: 30000
# Activer la propagation du contexte de requête

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # Hibernate properties
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# WebSocket Configuration
websocket:
  path: /ws-chat
  allowed-origins: "*"

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
    org:
      springframework:
        web:
          socket:
            handler: DEBUG
            socktjs: DEBUG
          messaging:
            simp:
              stomp: DEBUG

app:
  jwt:
    secret: TGHJVxyGBVg9oBpHJED2bECDujeT+gd3Hm1Uy2TE3N0Rv+m+mFE2oE/ucN692Wp6pwqKc9eVEk6SbHwHVwcykQ==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8405/eureka/
    register-with-eureka: true
    fetch-registry: true